asr_model:
  optimizer:
    type: 'Adadelta'                               # Optimizer used for training (not mentioned in LAS)      
    learning_rate: 1.0                             # Learning rate for opt (not mentioned in LAS)
  encoder:                                      
    state_size: 256                                # The state size of the LSTM used in the encoder (LAS approved)
  attention:                                             
    mlp_out_size: 128                              # The dimension projected to by the phi and psi nets
  decoder:                                             
    state_size: 512                                # The state size of the LSTM used in the decoder (LAS approved)
  tf_rate: 0.9                                     # Teacher forcing rate (LAS approved)
  feature_dim: 40                                  # Dimensionality of fbanks (has to be same as used in prepro) (LAS approved)

speech_autoencoder:
  kernel_sizes: [[36, 1], [1, 5], [1, 3]]          # A list of kernel sizes for the 3 convolutional layers
  num_filters: [32, 64, 256]                       # A list of output filters for the 3 convolutional layers
  pool_kernel_sizes: [[3, 1], [5, 1], [2000, 40]]  # A list of kernel sizes (only 3 values) for the max pooling of each convolutional layer

text_autoencoder:
  state_size: 256
  emb_dim: 128
  num_layers: 2

solver:
  # Paths to prepro indexes
  train_index_path: './data/ivona_processed/index.tsv'
  eval_index_path: './data/ivona_processed/eval_index.tsv'
  test_index_path: None
  n_jobs: 8                                        # Number of subprocesses used for Dataloader (LAS neutral)
  batch_size: 32                                   # training batch size (LAS approved)
  total_steps: 300000                              # total steps for training (LAS neutral)
  eval_batch_size: 32                              # validation batch size (LAS approved)                                                         
  eval_step: 1000                                  # interval of validation steps (not mentioned in LAS)
  # Path to pretrained LM
  decode_lm_path: 'result/complete_ivona_lm/rnnlm'
  # 
  decode_lm_weight: 0.5

