asr_model:
  optimizer:
    type: 'Adadelta'                          # Optimizer used for training (adam)
    learning_rate: 1.0                        # Learning rate for opt
  encoder:                                    ########## Encoder
    state_size: 256                           # RNN cell used in encoder, should be implemented in Pytorch
  attention:                                  ########## Attention : http://www.aclweb.org/anthology/D15-1166 section 3.1 for more details
    dim: 300                                  # The dimension of attention layer, only works when proj==True
    mlp_out_size: 128
  decoder:
    state_size: 256
  tf_rate: 0.9
  feature_dim: 40                             # this has to correspond with whatever dimension was used in prepro

solver:
  # Data options
  train_index_path: './data/processed/index.tsv'
  eval_index_path: './data/processed/eval_index.tsv'
  test_index_path: None
  n_jobs: 8                                   # Subprocess used for torch Dataloader
  max_timestep: 3000                          # Max length for audio feature (0 for no restriction)
  max_label_len: 400                          # Max length for output sequence (0 for no restriction)
  batch_size: 24                              # training batch size
  total_steps: 300000                         # total steps for training                         
  # Validation options
  eval_batch_size: 16                             
  eval_step: 2
  # Decoding options
  max_decode_step_ratio: 0.1
  decode_beam_size: 20
  decode_lm_path: 'result/complete_ivona_lm/rnnlm'
  decode_lm_weight: 0.5