asr:
  opt:
    type: 'Adadelta'
    learning_rate: 1.0
  mdl:
    encoder_state_size: 256
    mlp_out_size: 128
    decoder_state_size: 256
    tf_rate: 0.9
    feature_dim: 40

  train_index: './data/train.tsv'
  valid_index: './data/valid.tsv'
  test_index: './data/test.tsv'

  decode_beam_size: 3
  decode_jobs: 8
  max_decode_step_ratio: 0.25
  decode_lm_weight: 0.5

  wer_step: 50

sae:
  opt:
    type: 'Adam'
    learning_rate: 0.0001
  mdl:
    kernel_sizes: [[1, 36], [5, 1], [3, 1]]
    num_filters: [32, 64, 256]
    pool_kernel_sizes: [[3, 1], [5, 1], [2000, 40]]

  train_index: './data/train.tsv'
  valid_index: './data/valid.tsv'

  train_batch_size: 32
  eval_batch_size: 32
  n_epochs: 10
  valid_step: 1000
  save_step: 200
  logging_step: 1

tae:
  opt:
    type: 'Adam'
    learning_rate: 0.0001
  mdl:
    state_size: 256
    emb_dim: 128
    num_layers: 2
  drop_rate: 0.1

  train_index: './data/train.tsv'
  valid_index: './data/valid.tsv'

  train_batch_size: 64
  eval_batch_size: 64
  n_epochs: 50
  save_step: 2000
  valid_step: 1000
  logging_step: 1

adv:
  G_opt:
    type: 'Adadelta'
    learning_rate: 1.0
  D_opt:
    type: 'Adadelta'
    learning_rate: 1.0
  mdl:
    hidden_dim: 256
  label_smoothing: 0.1

  train_index: './data/train.tsv'
  valid_index: './data/valid.tsv'

  train_batch_size: 32
  eval_batch_size: 32

  n_epochs: 10
  save_step: 1000
  valid_step: 1000
  logging_step: 1

char_lm:
  opt:
    type: 'Adam'
    learning_rate: 0.0001
  mdl:
    hidden_size: 128
    tf_rate: 0.9

  train_index: './data/text_train.txt'
  valid_index: './data/text_eval.txt'

  chunk_size: 200

  train_batch_size: 128
  n_epochs: 8
  valid_step: 100
  logging_step: 1
  save_step: 50

seed_train:
  super_its: 5